// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3J0VF7BUMU55BtssUIaCH1gu7y6quHuk',
    appId: '1:766581429942:web:62d5fa479d0f4ff5153817',
    messagingSenderId: '766581429942',
    projectId: 'lost-and-found-a4fff',
    authDomain: 'lost-and-found-a4fff.firebaseapp.com',
    storageBucket: 'lost-and-found-a4fff.firebasestorage.app',
    measurementId: 'G-NFLF2LQ7XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzmoGFyDi4HdW8lV4w4YH94ElxFoy4YTg',
    appId: '1:766581429942:android:2b82f9c053f5503c153817',
    messagingSenderId: '766581429942',
    projectId: 'lost-and-found-a4fff',
    storageBucket: 'lost-and-found-a4fff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvg6JMJ6K7FYaJNl4A_Epm0JQm481HLCs',
    appId: '1:766581429942:ios:a0c97dcdeda7ce13153817',
    messagingSenderId: '766581429942',
    projectId: 'lost-and-found-a4fff',
    storageBucket: 'lost-and-found-a4fff.firebasestorage.app',
    iosClientId: '766581429942-6pff23psgsl98dc32rd1v4hb42qfd4r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvg6JMJ6K7FYaJNl4A_Epm0JQm481HLCs',
    appId: '1:766581429942:ios:a0c97dcdeda7ce13153817',
    messagingSenderId: '766581429942',
    projectId: 'lost-and-found-a4fff',
    storageBucket: 'lost-and-found-a4fff.firebasestorage.app',
    iosClientId: '766581429942-6pff23psgsl98dc32rd1v4hb42qfd4r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3J0VF7BUMU55BtssUIaCH1gu7y6quHuk',
    appId: '1:766581429942:web:d571da66983ab9e8153817',
    messagingSenderId: '766581429942',
    projectId: 'lost-and-found-a4fff',
    authDomain: 'lost-and-found-a4fff.firebaseapp.com',
    storageBucket: 'lost-and-found-a4fff.firebasestorage.app',
    measurementId: 'G-PVDZ3N3XRZ',
  );
}
